In [53]:
import pandas as pd

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [54]:
df=pd.read_csv("data-clean.csv")

In [55]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [56]:
df.isnull() # when the value is null it show true

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [57]:
df.isnull().sum() #from this it help to give the sum of null values .

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [58]:
df.dropna() #this is use to drop the null value in columns.

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [59]:
df.dropna(axis=1) # Drop columns with missing values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [60]:
df.fillna(0) #it help to fill the null with '0'.

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [61]:
df["Age"].fillna(df["Age"].mean())  # Replace with mean

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [62]:
df.ffill() # Forward fill

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [63]:
df.bfill() #backward fill

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [64]:
df.duplicated() #it show how much the dupicated rows are.

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [65]:
df.drop_duplicates() #it show the values which are duplicate .

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [66]:
df.duplicated(subset=["Name","Age"]) #show name and age duplicate.

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [67]:
df["City"].str.contains("delhi" ,case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [68]:
type(df["City"].str.contains("delhi" ,case=False))

pandas.Series

In [69]:
df["Email"].str.split('@')

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [70]:
df2=df.dropna().copy()

In [71]:
df["Age"]=df2["Age"].astype(int)

In [72]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      str
 1   Age        5 non-null      float64
 2   City       9 non-null      str
 3   Gender     9 non-null      str
 4   Email      9 non-null      str
 5   Join Date  8 non-null      str
dtypes: float64(1), str(5)
memory usage: 564.0 bytes

In [74]:
df["Name"].str.lower() # Converts all names to lowercase.

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: str

In [75]:
df["City"].str.contains("delhi", case=False) # Checks if 'delhi' is in the city name, case-insensitive.

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [76]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN   NaN        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [77]:
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [78]:
df2["Age Group"]=df2["Age"].apply(lambda x: "Adult" if x >=18 else "Minor")

In [79]:
df2

    Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [83]:
def isminor(x):
    return "Adult" if x>=18 else "Minor"
df2["Age Group"]=df2["Age"].apply(isminor) 
# as same as df2["Age Group"]=df2["Age"].apply(lambda x: "Adult" if x >=18 else "Minor")

In [82]:
df2

    Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [84]:
gender_map={"M":"Male","F":"Female","O":"Other"}
df2["Gender"]=df2["Gender"].map(gender_map)

In [85]:
df2

    Name   Age         City  Gender              Email   Join Date Age Group
0  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai    Male  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult

In [86]:
# .apply() → Apply any function to rows or columns
# .map() → Element-wise mapping for Series
# .replace() → Replace specific values

In [91]:
df2["City"]=df2["City"].replace({"Delhi": "New Delhi", "Mumbai": "New Mumbai"})
df2

    Name   Age         City  Gender              Email   Join Date Age Group
0  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David  22.0   New Mumbai    Male  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult