In [45]:
import pandas as pd

In [46]:
df = pd.read_csv("main.csv")

In [47]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [48]:
pd.read_csv("main.csv", usecols=["Actor", "Year"], nrows=10) #for perticular column.

                Actor  Year
0      Shah Rukh Khan  2023
1         Salman Khan  2017
2          Aamir Khan  2016
3       Ranbir Kapoor  2022
4       Ranveer Singh  2018
5  Ayushmann Khurrana  2018
6       Rajkummar Rao  2018
7      Hrithik Roshan  2019
8        Akshay Kumar  2019
9       Kartik Aaryan  2022

In [51]:
# Write CSV
df.to_csv("output.csv", index=False) #here new file is creater what u give the name in it like "output.csv".

In [58]:
# with pd.ExcelWriter("main.csv") as writer:
#     df1.to_excel(writer, sheet_name="Summary", index=False)
#     df2.to_excel(writer, sheet_name="Details", index=False )# use this for multiple sheets.

In [ ]:
# JSON Files
# Read JSON
# df = pd.read_json("data.json")